### ISSUE TITLE
Cannot Parse Error

### ISSUE THREAD

**Issue by Stephonomon** [Alkaar/resy-booking-bot#71]
When trying to run, I get the following error in the command line (Windows)

```
C:\Users\steph\resy>sbt
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 19.0.1)
[info] loading settings for project resy-build from plugins.sbt ...
[info] loading project definition from C:\Users\steph\resy\project
[info] loading settings for project resy-booking-bot from build.sbt ...
[info] set current project to resy-booking-bot (in build file:/C:/Users/steph/resy/)
[info] sbt server started at local:sbt-server-d4f3cfa4d78bd1a3a4ab
[info] started sbt server
```

```C:\Users\steph\resy>sbt run
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 19.0.1)
[info] loading settings for project resy-build from plugins.sbt ...
[info] loading project definition from C:\Users\steph\resy\project
[info] loading settings for project resy-booking-bot from build.sbt ...
[info] set current project to resy-booking-bot (in build file:/C:/Users/steph/resy/)
[info] compiling 5 Scala sources to C:\Users\steph\resy\target\scala-2.13\classes ...
[warn] 1 deprecation (since 2.13.3); re-run with -deprecation for details
[warn] one warning found
[info] running com.resy.ResyBookingBot
[INFO ] 2022-11-29 23:58:32.967-05:00 ResyBookingBot$:16 - Starting Resy Booking Bot
[error] pureconfig.error.ConfigReaderException: Cannot convert configuration to a com.resy.ResyKeys. Failures are:
[error]   - (resyConfig.conf @ jar:file:/C:/Users/steph/resy/target/bg-jobs/sbt_f3f74d62/job-1/target/f7a10fea/917659ec/resy-booking-bot_2.13-HEAD+20221129-2358.jar!/resyConfig.conf: 56) Unable to parse the configuration: Expecting end of input or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf).
[error]
[error]         at pureconfig.ConfigSource.loadOrThrow(ConfigSource.scala:81)
[error]         at pureconfig.ConfigSource.loadOrThrow$(ConfigSource.scala:78)
[error]         at pureconfig.ConfigSource$$anon$2.loadOrThrow(ConfigSource.scala:332)
[error]         at com.resy.ResyBookingBot$.main(ResyBookingBot.scala:19)
[error]         at com.resy.ResyBookingBot.main(ResyBookingBot.scala)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) pureconfig.error.ConfigReaderException: Cannot convert configuration to a com.resy.ResyKeys. Failures are:
[error]   - (resyConfig.conf @ jar:file:/C:/Users/steph/resy/target/bg-jobs/sbt_f3f74d62/job-1/target/f7a10fea/917659ec/resy-booking-bot_2.13-HEAD+20221129-2358.jar!/resyConfig.conf: 56) Unable to parse the configuration: Expecting end of input or a comma, got '=' (if you intended '=' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf).
[error] Total time: 10 s, completed Nov 29, 2022, 11:58:33 PM```

**Comment by Stephonomon** [comment]
NM, I left this null. resDetails.res-time-types
